In [1]:
import random

In [3]:
random.choice((1 , 2 , 3 , 4 , 5))

3

In [4]:
random.choice("Rupam")

'm'

In [9]:
random.choice(range(0 ,11))

1

In [11]:
random.randrange(1 , 10)

2

In [12]:
random.random()

0.7240373007155714

In [16]:
l = [1 , 2 ,3  , 4]
random.shuffle(l)
l


[1, 2, 4, 3]

In [19]:
random.uniform(7 , 14)

7.216148885868189

In [20]:
import numpy as np


In [21]:
np.random.random_sample()

0.7138800985214209

In [22]:
np.random.random_sample(5)

array([0.95159165, 0.65009556, 0.77339384, 0.15533563, 0.53370708])

In [23]:
np.random.rand(5)

array([0.80866277, 0.03349252, 0.11158603, 0.23529631, 0.18141497])

In [25]:
np.random.rand(3 , 2)

array([[0.13628151, 0.78234172],
       [0.74807876, 0.25859704],
       [0.56887977, 0.10128856]])

In [27]:
arr = np.random.randint(1 , 5 , size=(3 , 4))

In [28]:
arr

array([[1, 1, 2, 2],
       [3, 2, 4, 2],
       [1, 2, 2, 2]], dtype=int32)

In [29]:
arr.reshape(2 , 6)

array([[1, 1, 2, 2, 3, 2],
       [4, 2, 1, 2, 2, 2]], dtype=int32)

In [30]:
arr.reshape(2 , -2)

array([[1, 1, 2, 2, 3, 2],
       [4, 2, 1, 2, 2, 2]], dtype=int32)

In [36]:
arr1 = np.random.randint(1 , 10 , size=(4 , 3))

In [37]:
arr1 > 3

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]])

In [38]:
arr1[0:3 , 1:3]

array([[1, 6],
       [4, 8],
       [4, 8]], dtype=int32)

In [ ]:
arr2 = np.random.randint(1 , 10 , (3 , 4))
arr1 * arr2 # element wise multiplication

In [39]:
arr2 = np.random.randint(1 , 10 , (3 , 4))
arr1 = np.random.randint(1 , 10 , (4 , 3))

In [40]:
arr2 @ arr1

array([[ 92, 112,  48],
       [126, 150,  98],
       [139, 176,  83]], dtype=int32)